version: "2.4" # Version 2 allows health checking outside of docker stack.

services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=secret --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 3s
      retries: 30

#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./data/prometheus:/prometheus
#      - ./resources/docker/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#
#  grafana:
#    image: grafana/grafana:latest
#    volumes:
#      - ./resources/docker/grafana.ini:/etc/grafana/grafana.ini
#      - ./resources/docker/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
#      - ./resources/docker/dashboards:/etc/grafana/provisioning/dashboards
#    ports:
#      - 3001:3000
#    links:
#      - prometheus
#
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "16686:16686"

  # Waiter blocks until required services are up.
  waiter:
    depends_on:
      database:
        condition: service_healthy
    image: busybox
